- id: letsencrypt-renewal
  alias: Let's Encrypt Renewal
  trigger:
  - platform: time
    at: 00:00:00
  action:
  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt
- alias: Weekday Morning Blind Up
  description: Opens the lounge blinds on weekdays only.
  trigger:
  - platform: time
    at: '05:30:00'
  - event: sunrise
    offset: -00:15:00
    platform: sun
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - condition: sun
    after: sunrise
    after_offset: "-00:16:00"
  - condition: time
    after: '05:30:00'
  action:
    - service: cover.set_cover_position
      data:
        # Open Night Blind
        entity_id: cover.lounge_night_blind_level
        position: 100
    - service: cover.set_cover_position
      data:
        # Half Open Day Blind
        entity_id: cover.lounge_day_blind_level
        position: 50
- alias: Weekend Morning Blind Up
  description: Opens both lounge blinds on weekends only.
  trigger:
  - platform: time
    at: '07:30:00'
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  action:
    - service: cover.set_cover_position
      data:
        # Open Night Blind
        entity_id: cover.lounge_night_blind_level
        position: 100
    - service: cover.set_cover_position
      data:
        # Open Day Blind
        entity_id: cover.lounge_day_blind_level
        position: 100
- alias: Weekday Sunset Blind Down
  description: Closes the lounge blind on weekdays at sunset.
  trigger:
  - event: sunset
    offset: 00:15:00
    platform: sun
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
    - service: cover.set_cover_position
      data:
        # Close Night Blind
        entity_id: cover.lounge_night_blind_level
        position: 10
    - service: cover.set_cover_position
      data:
      # Open Day Blind
        entity_id: cover.lounge_day_blind_level
        position: 100
- alias: Weekday Morning Coffee On
  description: Turns on the coffee machine on weekdays only.
  trigger:
    platform: time
    at: 06:50:00
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - device_id: 008d92cbcfbd4c078a17f6cf715d7be8
    domain: switch
    entity_id: switch.coffee_machine
    type: turn_on
  id: 831bcf8e95e44bf4b270f9bce427e025
- id: weekday_morning_coffee_off
  alias: Weekday Morning Coffee Off
  description: Turns off the coffee machine on weekdays only.
  trigger:
  - at: 08:40:00
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - device_id: 008d92cbcfbd4c078a17f6cf715d7be8
    domain: switch
    entity_id: switch.coffee_machine
    type: turn_off
- alias: Saturday Morning Coffee On
  description: Turns on the coffee machine on Saturdays only.
  trigger:
    platform: time
    at: 09:30:00
  condition:
  - condition: time
    weekday:
    - sat
  action:
  - device_id: 008d92cbcfbd4c078a17f6cf715d7be8
    domain: switch
    entity_id: switch.coffee_machine
    type: turn_on
  id: 73402729d9ba467ab7bb085b4af6f943
- alias: Midday Coffee Off
  description: Turns off the coffee machine at midday.
  trigger:
    platform: time
    at: '12:15:00'
  condition: []
  action:
  - device_id: 008d92cbcfbd4c078a17f6cf715d7be8
    domain: switch
    entity_id: switch.coffee_machine
    type: turn_off
  id: 2026d3ca0fdb42c98f0ccfc962cca5a6
- alias: One Off Coffee On
  description: Turns off the coffee machine on a date.
  trigger:
    platform: time
    at: '06:00:00'
  condition:
    condition: template
    value_template: '{{ now().date() | string == "2020-01-25" }}'
  action:
  - device_id: 008d92cbcfbd4c078a17f6cf715d7be8
    domain: switch
    entity_id: switch.coffee_machine
    type: turn_on
- id: sunset_inside_lights_on
  alias: Sunset Inside Lights On
  description: Turns On the inside lights 15 minutes before sunset.
  trigger:
  - event: sunset
    offset: -00:15:00
    platform: sun
  condition: []
  action:
  - device_id: bb50c1b4188248389cd28d1cb0bf4981
    domain: switch
    entity_id: switch.stairway_light
    type: turn_on
  - device_id: 973e3076a1884208ac33b8f13ba175c2
    domain: switch
    entity_id: switch.entry_light
    type: turn_on
- id: sunset_outside_lights_on
  alias: Sunset Outside Lights On
  description: Turns On the outside lights 15 minutes after sunset.
  trigger:
  - event: sunset
    offset: 00:15:00
    platform: sun
  condition: []
  action:
  - device_id: 8114bd12a99549188aa6e2836fb0aa9f
    domain: switch
    entity_id: switch.outside_light
    type: turn_on
- id: midnight_outside_light_off
  alias: Midnight Outside Light Off
  description: ''
  trigger:
  - at: '23:00'
    platform: time
  condition: []
  action:
  - device_id: 8114bd12a99549188aa6e2836fb0aa9f
    domain: switch
    entity_id: switch.outside_light
    type: turn_off
- id: morning_aircon
  alias: Morning AirCon
  description: ''
  trigger:
  - at: 05:00:00
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.upstairs
        temperature: 22