##################
# default_config #
##################
automation: !include automations.yaml
#backup:
bluetooth:
cloud:
config:
# counter:

dhcp:
energy:
frontend:
history:
  exclude:
    domains:
      - automation
      - device_tracker
  include:
    entities:
     - device_tracker.glen_ping
     - device_tracker.glen_unifi
     - device_tracker.glen_s_s20_ultra
     - device_tracker.nat_iphonedetect
     - device_tracker.nat_unifi
     - device_tracker.nat_ping
     - device_tracker.nat_phone
homeassistant_alerts:
input_boolean:
input_button:
input_datetime:
input_number:
input_select:
input_text:
logbook:
map:
media_source:
mobile_app:
my:
person:
scene: !include scenes.yaml
script: !include scripts.yaml
ssdp:
stream:
sun:
system_health:
# tag:
# timer:
#usb:
#webhook:
zeroconf:
#zone:
#####################
# end default_config#
#####################

group: !include groups.yaml

homeassistant:
  packages: !include_dir_named packages
  country: AU

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Text to speech
tts:
  - platform: google_translate
    service_name: google_translate_say

system_log:
  max_entries: 200

route53:
  aws_access_key_id: !secret aws_access_key_id
  aws_secret_access_key: !secret aws_secret_access_key
  zone: Z3EDDQO2J86T2O
  domain: buktenica.com
  records:
    - york

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

smartir:
climate:
  - platform: smartir
    name: Lounge AC
    unique_id: lounge_ac
    device_code: 1281
    controller_data: remote.lounge_broadlink_remote
    temperature_sensor: sensor.lounge_room_temperature
    humidity_sensor: sensor.lounge_room_humidity
    power_sensor: binary_sensor.lounge_ac_power

light:
  - platform: group
    name: Office Lights
    entities:
      - light.0146087784cca88b6294
      - light.0000178484cca88bafb5
      - light.0146087784cca88bbee1
      - light.0000178484cca88bafd1

