esphome:
  name: ${device_name}
  # on_boot:
  #   - lambda: |-
  #       id(ota_id).set_auth_password("REPLACE_ME");
  
esp8266:
  board: esp01_1m

output:
  - platform: gpio
    id: relay
    pin: GPIO12

light:
  - platform: binary
    id: ${id}
    name: ${name}
    output: relay

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO04
    name: "${name} input"
    ${button_action}:
      then:
        - light.toggle: ${id}