esphome:
  name: ${device_name}
esp8266:
  board: esp01_1m
  # on_boot:
  #   - lambda: |-
  #       id(ota_id).set_auth_password("REPLACE_ME");
light:
  - platform: rgb
    name: ${light_name}
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    effects:
      - random:
      - strobe:
      - flicker:

output:
  - platform: esp8266_pwm
    pin: GPIO12
    frequency: 1000 Hz
    id: pwm_r

  - platform: esp8266_pwm
    pin: GPIO15
    frequency: 1000 Hz
    id: pwm_g

  - platform: esp8266_pwm
    pin: GPIO14
    frequency: 1000 Hz
    id: pwm_b

  - platform: esp8266_pwm
    pin: GPIO4
    frequency: 1000 Hz
    id: pwm_w