substitutions:
  device_name: backyard-s25
  channel_1: Backyard Light
  channel_2: Garden Switch
  max_power: "2000.0" # watt
  max_temp: "80.0" # °C
  ip: "10.4.4.33"
  use_ip: ${ip}
  ssid: IoTL1
  button_action: "on_press" #on_state
#####################################
packages:
  common_base: !include common/base.yaml
  device_base: !include common/s25-light.yaml
