substitutions:
  device_name: bedroom-night-s25
  friendly_name: Night Blind
  open_duration: 37sec
  close_duration: 37sec
  ip: "10.4.4.41"
  use_ip: ${ip}
  ssid: IoTL2


  open_switch: switch2
  open_relay: relay1

  close_switch: switch1
  close_relay: relay2
#####################################
packages:
  common_base: !include common/base.yaml
  device_base: !include common/s25-cover.yaml
#####################################
