substitutions:
  device_name: car-esp
  channel_1: "Car"
  ip: "10.4.4.42"
  ssid: IoTG
  board: nodemcu-32s
  height: "1.2" # height in metres
#######################
esphome:
  name: ${device_name}

esp32:
  board: ${board}

wifi:
  ssid: ${ssid}
  password: !secret iot
  fast_connect: on
  use_address: ${ip}
  manual_ip:
    static_ip: ${ip}
    gateway: 10.4.4.1
    subnet: 255.255.255.0

  # Enable fallback hotspot  in case wifi connection fails
  ap:
    ssid: ${device_name}
    password: !secret iot
    manual_ip:
      static_ip: 192.168.100.2
      gateway: 192.168.100.1
      subnet: 255.255.255.0

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret iot

ota:
  password: !secret iot

time:
  - platform: homeassistant
    id: homeassistant_time
#####################################
sensor:
  - platform: ultrasonic
    id: ultrasonic1
    name: "Car_position"
    trigger_pin: GPIO25
    echo_pin: GPIO26
    update_interval: 10s

binary_sensor:
  - platform: template
    name: "Car Present"
    icon: "mdi:car"
    lambda: |-
      if (id(ultrasonic1).state < ${height}) {
        // Car  is present.
        return true;
      } else {
        // Car is not present.
        return false;
      }