substitutions:
  device_name: car-esp
  channel_1: "Car"
  ip: "10.4.4.42"
  ssid: IoTG
  height: "1.2" # height in metres
#######################
esphome:
  name: ${device_name}
esp32:
  board: nodemcu-32s
  # https://esphome.io/devices/nodemcu_esp32.html

packages:
  common_base: !include common/base.yaml
#####################################
sensor:
  - platform: ultrasonic
    id: ultrasonic1
    name: "Car_position"
    trigger_pin: GPIO25
    echo_pin: GPIO26
    update_interval: 10s

binary_sensor:
  - platform: template
    name: "Car Present"
    icon: "mdi:car"
    lambda: |-
      if (id(ultrasonic1).state < ${height}) {
        // Car  is present.
        return true;
      } else {
        // Car is not present.
        return false;
      }