substitutions:
  device_name: dryer
  max_temp: "90.0" # °C
  ip: "10.4.4.53"
  use_ip: ${ip}
  ssid: IoTL1
  # Higher value gives lower watt readout
  current_res: "0.00012"
  # Lower value gives lower voltage readout
  voltage_div: "1925"
  restore_mode: "RESTORE_DEFAULT_ON"
  update_interval: "30s"
#####################################
packages:
  common_base: !include common/base.yaml
  device_base: !include common/plus1pm-switch.yaml
#####################################