substitutions:
  device_name: front-esp
  ip: "10.4.4.27"
  use_ip: ${ip}
  ssid: IoTL1
  platform: "esp8266"
  board: nodemcuv2
  # https://esphome.io/devices/nodemcu_esp8266.html
#####################################
packages:
  common_base: !include common/base.yaml
  device_base: !include common/generic.yaml
#####################################

binary_sensor:
  - platform: gpio
    pin:
      number: D5
      mode:
        input: true
        pullup: true
    name: "Entry Door"
    device_class: door
    filters:
      - delayed_on: 10ms
  - platform: gpio
    pin:
      number: D6
      mode:
        input: true
        pullup: true
    name: "Front BiFold Door"
    device_class: door
    filters:
      - delayed_on: 10ms
sensor:
  - platform: dht
    model: DHT22
    pin: D7
    temperature:
      name: "Lounge Room Temperature"
    humidity:
      name: "Lounge Room Humidity"
    update_interval: 30s
