substitutions:
  device_name: garagerear-esp
  channel_1: "Garage Rear Door"
  channel_2: "Garage Rear Button"
  ip: "10.4.4.45"
  ssid: IoTG
#####################################
esphome:
  name: ${device_name}
  platform: ESP8266
  board: nodemcuv2

packages:
  common_base: !include common/base.yaml
#####################################

binary_sensor:
  - platform: gpio
    pin:
      number: D1
      mode:
        input: true
        pullup: true
    name: ${channel_1}
    device_class: door
    filters:
      - delayed_on: 10ms
  - platform: gpio
    pin:
      number: D2
      mode:
        input: true
        pullup: true
    name: ${channel_2}
    filters:
      - delayed_on: 10ms
      - invert
