substitutions:
  device_name: garage-esp32s3
  ip: "10.4.4.80"
  use_ip: ${ip}
#####################################
packages:
  common_base: !include common/base-rj45.yaml
  device_base: !include common/esp32-s3-base.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: D1
      mode:
        input: true
        pullup: true
    name: ${channel_1}
    device_class: door
    filters:
      - delayed_on: 10ms
  - platform: gpio
    pin:
      number: D2
      mode:
        input: true
        pullup: true
    name: ${channel_2}
    filters:
      - delayed_on: 10ms
      - invert