substitutions:
  device_name: garage-s25
  channel_1: Garage Light
  channel_2: Garage Door
  max_power: "2000.0" # watt
  max_temp: "100.0" # °C
  ip: "10.4.4.46"
  use_ip: ${ip}
  ssid: IoTG
  button_action: "on_state" #on_press
#######################
packages:
  common_base: !include common/base.yaml
  device_base: !include common/s25-light.yaml
#####################################
