substitutions:
  device_name: garden
  channel_1: garden_lights
  channel_2: party_lights
  max_power: "2000.0" # watt
  max_temp: "80.0" # °C
  ip: "10.4.4.50"
  use_ip: ${ip}
  ssid: IoTL1
#####################################
packages:
  common_base: !include common/base.yaml
  device_base: !include common/2pm-light.yaml