substitutions:
  device_name: hall-1pm
  channel_1: "Hall Light"
  ip: "10.4.4.32"
  ssid: IoTL2
  calibrate: "15000 -> 1400"
#####################################
packages:
  common_base: !include common/base.yaml
  device_base: !include common/1pm-light.yaml