substitutions:
  device_name: laundry-light-s25
  channel_1: Laundry Light
  channel_2: No Light
  max_power: "2000.0" # watt
  max_temp: "80.0" # °C
  ip: "10.4.4.35"
  use_ip: ${ip}
  ssid: IoTL1
  calibrate: "15000 -> 1400"
  button_action: "on_state" #on_press
#####################################
packages:
  common_base: !include common/base.yaml
  device_base: !include common/s25-light.yaml
