substitutions:
  device_name: laundry-fan-mini
  id: Laundry Fan
  name: "Laundry Fan"
  ip: "10.4.4.23"
  use_ip: ${ip}
  ssid: IoTL1
  board: esp01_1m
#####################################
packages:
  common_base: !include common/base.yaml
  device_base: !include common/mini-base.yaml
#####################################
switch:
  - platform: gpio
    id: relay
    pin: GPIO12
    name: ${name}
    icon: "mdi:fan"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO04
    name: "${name} input"
    on_state:
      then:
        - switch.toggle: relay