substitutions:
  device_name: laundry-light-1pm
  channel_1: laundry_light
  ip: "10.4.4.22"
  use_ip: ${ip}
  ssid: IoTL1
  calibrate: "15000 -> 1400"
  button_action: "on_state" #on_press
#####################################
packages:
  common_base: !include common/base.yaml
  device_base: !include common/1pm-light.yaml
