substitutions:
  device_name: lounge-night-s25
  friendly_name: Night Blind
  open_duration: 37sec
  close_duration: 37sec
  ip: "10.4.4.41"
  ssid: IoTL1
  open_switch: switch1
  open_relay: relay2
  close_switch: switch2
  close_relay: relay1
#####################################
packages:
  common_base: !include common/base.yaml
  device_base: !include common/s25-cover.yaml