substitutions:
  device_name: lounge-fr
  light_name: FR
  ip: "10.4.4.58"
  ssid: IoTL1
#####################################
packages:
  common_base: !include common/base.yaml
  device_base: !include common/dimmer2.yaml