substitutions:
  device_name: lounge-rgb
  light_name: Lounge RGB
  ip: "10.4.4.69"
  use_ip: ${ip}
  ssid: IoTL1
#####################################
packages:
  common_base: !include common/base.yaml
  device_base: !include common/rgbw2.yaml