substitutions:
  device_name: lounge-rr
  light_name: RR
  ip: "10.4.4.55"
  ssid: IoTL1
#####################################
packages:
  common_base: !include common/base.yaml
  device_base: !include common/dimmer2.yaml