substitutions:
  device_name: mancave-s25
  channel_1: "Mancave Light"
  channel_1: "Mancave Light"
  max_power: "2000.0" # watt
  max_temp: "80.0" # °C
  ip: "10.4.4.45"
  use_ip: ${ip}
  ssid: IoTL2
  button_action: "on_press" #on_state
#####################################
packages:
  common_base: !include common/base.yaml
  device_base: !include common/s25-light.yaml