substitutions:
  device_name: mancave-1pm
  channel_1: "Mancave Light"
  ip: "10.4.4.47"
  ssid: IoTL2
  calibrate: "163 -> 18"
  button_action: "on_press" #on_state
#####################################
packages:
  common_base: !include common/base.yaml
  device_base: !include common/1pm-light.yaml