substitutions:
  device_name: rear-1pm
  channel_1: "Rear Bifold Door"
  ip: "10.4.4.43"
  use_ip: ${ip}
  ssid: IoTL1
#####################################
esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

packages:
  common_base: !include common/base.yaml
#####################################

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      #mode: INPUT_PULLUP
      inverted: True
    name: ${channel_1}
    id: switchid
    device_class: door