substitutions:
  device_name: rear-1pm
  channel_1: "Rear Bifold Door"
  ip: "10.4.4.43"
  ssid: IoTL1
  board: esp01_1m
#####################################
esphome:
  name: ${device_name}
  platform: ESP8266
  board: ${board}

wifi:
  ssid: ${ssid}
  password: !secret iot
  fast_connect: on
  use_address: ${ip}
  manual_ip:
    static_ip: ${ip}
    gateway: 10.4.4.1
    subnet: 255.255.255.0

  # Enable fallback hotspot  in case wifi connection fails
  ap:
    ssid: ${device_name}
    password: !secret iot
    manual_ip:
      static_ip: 192.168.100.2
      gateway: 192.168.100.1
      subnet: 255.255.255.0

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api

ota:
  password: !secret iot

time:
  - platform: homeassistant
    id: homeassistant_time
#####################################

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      #mode: INPUT_PULLUP
      inverted: True
    name: ${channel_1}
    id: switchid
    device_class: door