substitutions:
  device_name: server-esp
  ip: "10.4.4.29"
  use_ip: ${ip}
  name: "Server"
  ssid: IoTL2
  platform: "esp8266"
  board: nodemcuv2
  # https://esphome.io/devices/nodemcu_esp8266.html
#####################################
packages:
  common_base: !include common/base.yaml
  device_base: !include common/generic.yaml
#####################################

sensor:
  - platform: dht
    model: DHT22
    pin: D1
    temperature:
      name: ${name} 
      id: fan_temperature
      accuracy_decimals: 3
      filters:
         - exponential_moving_average:  
             alpha: 0.1
             send_every: 1
    humidity:
      name: ${name} Humidity
    update_interval: 10s

output:
  - platform: esp8266_pwm
    id: output_fan
    pin: D2
    frequency: 20000 Hz

fan:
  - platform: speed
    output: output_fan
    name: ${name} Fan

climate:
  - platform: pid
    name:  ${name} PID
    id: thermostat
    sensor: fan_temperature

    default_target_temperature: 26°C
    cool_output: output_fan
        
    # The extents of the HA Thermostat
    visual:
      min_temperature: 20 °C
      max_temperature: 50 °C
  
    control_parameters:
      kp: 0.3
      ki: 0.0015
      kd: 0
      max_integral: 0.0
      output_averaging_samples: 1
      derivative_averaging_samples: 5

    # How to behave when close to the target temperature?
    deadband_parameters:
      threshold_high: 0.4°C
      threshold_low: -1.0°C
      kp_multiplier: 0.0
      ki_multiplier: 0.04
      kd_multiplier: 0.0
      deadband_output_averaging_samples: 15