substitutions:
  device_name: server-esp
  ip: "10.4.4.29"
  name: "Server"
  ssid: IoTL2
  board: nodemcuv2
  # https://esphome.io/devices/nodemcu_esp8266.html
#####################################
esphome:
  name: ${device_name}
  platform: ESP8266
  board: ${board}

wifi:
  ssid: ${ssid}
  password: !secret iot
  fast_connect: on
  use_address: ${ip}
  manual_ip:
    static_ip: ${ip}
    gateway: 10.4.4.1
    subnet: 255.255.255.0

  # Enable fallback hotspot  in case wifi connection fails
  ap:
    ssid: ${device_name}
    password: !secret iot
    manual_ip:
      static_ip: 192.168.100.2
      gateway: 192.168.100.1
      subnet: 255.255.255.0

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api

ota:
  platform: esphome
  id: ota_id
  password: !secret ota

time:
  - platform: homeassistant
    id: homeassistant_time
#####################################
sensor:
  - platform: dht
    model: DHT22
    pin: D0
    temperature:
      name: ${name} Temperature
    humidity:
      name: ${name} Humidity
    update_interval: 30s

output:
  - platform: esp8266_pwm
    id: output_fan
    pin: D2
    frequency: 20000 Hz

fan:
  - platform: speed
    output: output_fan
    name: ${name} Fan
