substitutions:
  device_name: server-esp
  ip: "10.4.4.29"
  name: "Server"
  ssid: IoTL2
  # https://esphome.io/devices/nodemcu_esp8266.html
#####################################
esphome:
  name: ${device_name}
  platform: ESP8266
  board: nodemcuv2

packages:
  common_base: !include common/base.yaml
#####################################
sensor:
  - platform: dht
    model: DHT22
    pin: D0
    temperature:
      name: ${name} Temperature
    humidity:
      name: ${name} Humidity
    update_interval: 30s

output:
  - platform: esp8266_pwm
    id: output_fan
    pin: D2
    frequency: 20000 Hz

fan:
  - platform: speed
    output: output_fan
    name: ${name} Fan
