substitutions:
  device_name: awning
  ip: "10.4.4.59"
  ssid: IoTL1
#######################
esphome:
  name: ${device_name}
esp32:
  board type: sp32doit-devkit-v1

packages:
  common_base: !include common/base.yaml
#####################################
