substitutions:
  device_name: stairs-1pm
  channel_1: "Stairway Light"
  ip: "10.4.4.37"
  ssid: IoTL2
  calibrate: "196 -> 12"
#####################################
packages:
  common_base: !include common/base.yaml
  device_base: !include common/1pm-light.yaml