substitutions:
  device_name: strata-1pm
  channel_1: "Strata Lights"
  ip: "10.4.4.70"
  ssid: IoTG
  calibrate: "196 -> 12"
#####################################
packages:
  common_base: !include common/base.yaml
  device_base: !include common/1pm-light.yaml