substitutions:
  device_name: wardrobe-1pm
  channel_1: "Wardrobe Light"
  ip: "10.4.4.38"
  ssid: IoTL2
  calibrate: "187 -> 12"
#####################################
packages:
  common_base: !include common/base.yaml
  device_base: !include common/1pm-light.yaml