substitutions:
  device_name: washer
  max_power: "2000.0" # watt
  max_temp: "90.0" # °C
  ip: "10.4.4.54"
  ssid: IoTL1
  # Higher value gives lower watt readout
  current_res: "0.001"
  # Lower value gives lower voltage readout
  voltage_div: "1925"
  restore_mode: "RESTORE_DEFAULT_ON"
#####################################
packages:
  common_base: !include common/base.yaml
  common_base: !include common/plus1pm-switch.yaml
#####################################
