homeassistant:
  customize:
     light.stairway_light:
       icon: mdi:lightbulb
     light.entry_light:
       icon: mdi:lightbulb
     light.kitchen_light:
       icon: mdi:lightbulb
     light.dining_light:
       icon: mdi:lightbulb
     light.lounge_frontleft:
       icon: mdi:lightbulb
     light.lounge_frontright:
       icon: mdi:lightbulb
     light.lounge_rearleft:
       icon: mdi:lightbulb
     light.lounge_rearright:
       icon: mdi:lightbulb
     light.outside_light:
       icon: mdi:lightbulb
     light.rear_outside:
       icon: mdi:lightbulb
     light.garden_lights:
       icon: mdi:lightbulb
     light.party_lights:
       icon: mdi:lightbulb
     light.hall_light:
       icon: mdi:lightbulb

light:
  - platform: switch
    name: Stairway Light
    entity_id: switch.stairway_light
  - platform: switch
    name:  Entry Light
    entity_id: switch.entry_light
  - platform: switch
    name: Kitchen Light
    entity_id: switch.kitchen_light
  - platform: switch
    name: Dining Light
    entity_id: switch.dining_light
  - platform: switch
    name: Lounge FL Light
    entity_id: switch.lounge_frontleft
  - platform: switch
    name: Lounge FR Light
    entity_id: switch.lounge_frontright
  - platform: switch
    name: Lounge RL Light
    entity_id: switch.lounge_rearleft
  - platform: switch
    name: Lounge RR Light
    entity_id: switch.lounge_rearlright
  - platform: switch
    name: Outside Light
    entity_id: switch.outside_light
  - platform: switch
    name: Rear Outside Light
    entity_id: switch.rear_outside
  - platform: switch
    name: Garden Lights
    entity_id: switch.garden_lights
  - platform: switch
    name: Party Lights
    entity_id: switch.party_lights
  - platform: switch
    name: Hall Light
    entity_id: switch.hall_light