automation:
  - id: tesla_solar_charging_start
    alias: Tesla Solar Charging Start
    trigger:
    - platform: numeric_state
      entity_id: sensor.energy_meter_total_watts
      below: '-1000'
      for: 00:05:00
    - platform: time
      at: 09:05:00
    - platform: state
      entity_id: binary_sensor.tesla_wall_connector_vehicle_connected
      to: 'on'
    condition:
    - condition: state
      entity_id: binary_sensor.tesla_wall_connector_vehicle_connected
      state: 'on'
    - condition: state
      entity_id: input_boolean.charging_override
      state: 'off'
    - condition: template
      value_template: >-
        {{ (states('sensor.lucy_battery') | int + 2 ) < states('number.lucy_charge_limit') | int }}
    - condition: time
      after: 09:00:00
      before: '15:00:00'
    action:
    - condition: state
      entity_id: binary_sensor.tesla_wall_connector_contactor_closed
      state: 'off'
    - service: switch.turn_on
      data:
        entity_id:
        - switch.lucy_charger
    - delay:
        minutes: 1
    - service: button.press
      target:
        entity_id: button.lucy_force_data_update
    - service: notify.mobile_app_s21
      data:
        message: clear_notification
        data:
          tag: charging
    - delay:
        seconds: 10
    - service: notify.mobile_app_s21
      data:
        message: "Lucy Started Charging at {{ states('sensor.lucy_battery')}}%"
        data:
          tag: charging

  - id: tesla_charging_stop
    alias: Tesla Charging Stop
    trigger:
    - platform: numeric_state
      entity_id: sensor.energy_meter_total_watts
      above: '100'
      for: 00:15:00
    - platform: time
      at: '14:59'
    - platform: state
      entity_id: binary_sensor.tesla_wall_connector_contactor_closed
      to: 'on'
    condition:
      or:
        - condition: time
          before: 09:00:00
          after: '14:58:00'
        - condition: numeric_state
          entity_id: sensor.energy_meter_total_watts
          above: '100'
    action:
    - condition: state
      entity_id: binary_sensor.tesla_wall_connector_contactor_closed
      state: 'on'
    - condition: state
      entity_id: input_boolean.charging_override
      state: 'off'
    - service: switch.turn_off
      data:
        entity_id:
        - switch.lucy_charger

  - id: tesla_charging_stopped
    alias: Tesla Charging Stopped
    trigger:
    - platform: state
      entity_id: binary_sensor.tesla_wall_connector_contactor_closed
      to: 'off'
    - condition: state
      entity_id: binary_sensor.tesla_wall_connector_vehicle_connected
      state: 'on'
    action:
    - service: button.press
      target:
        entity_id: button.lucy_force_data_update
    - service: notify.mobile_app_s21
      data:
        message: clear_notification
        data:
          tag: charging
    - delay:
        seconds: 10
    - service: notify.mobile_app_s21
      data:
        message: "Lucy Stopped Charging at {{ states('sensor.lucy_battery')}}%"
        data:
          tag: charging

  - id: tesla_solar_charging_more
    alias: Tesla Solar Charging More
    mode: single
    trigger:
    - platform: numeric_state
      entity_id: sensor.energy_meter_total_watts
      below: '-1000'
      for:
        minutes: 2
    - platform: numeric_state
      entity_id: sensor.energy_meter_total_watts
      below: '-1000'
      for:
        minutes: 4
    - platform: state
      entity_id: binary_sensor.tesla_wall_connector_contactor_closed
      to: 'on'
      for:
        minutes: 2
    condition:
    - condition: state
      entity_id: binary_sensor.tesla_wall_connector_contactor_closed
      state: 'on'
    - condition: state
      entity_id: input_boolean.charging_override
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.energy_meter_total_watts
      below: '-1000'
    action:
    - service: number.set_value
      data_template:
        entity_id: number.lucy_charging_amps
        value: >
          {% set charge = (states('number.lucy_charging_amps')|int) %}
          {% set grid = (states('sensor.energy_meter_total_watts')|int) %}
          {% if grid < -3800 %}
            {% set result = charge + 5 |int %}
          {% elif grid < -3000 %}
            {% set result = charge + 4 |int %}
          {% elif grid < -2300 %}
            {% set result = charge + 3 |int %}
          {% elif grid < -1600 %}
            {% set result = charge + 2 |int %}
          {% else %}
            {% set result = charge + 1 |int %}
          {% endif %}
          {{ result }}
    - delay:
        minutes: 1
    - service: button.press
      target:
        entity_id: button.lucy_force_data_update
    - service: notify.mobile_app_s21
      data:
        message: clear_notification
        data:
          tag: charging
    - delay:
        seconds: 10
    - service: notify.mobile_app_s21
      data:
        message: "Lucy Charging at {{ states('number.lucy_charging_amps')}} Amps"
        data:
          tag: charging

  - id: tesla_solar_charging_less
    alias: Tesla Solar Charging less
    mode: single
    trigger:
    - platform: numeric_state
      entity_id: sensor.energy_meter_total_watts
      above: '0'
      for:
        minutes: 2
    - platform: numeric_state
      entity_id: sensor.energy_meter_total_watts
      above: '0'
      for:
        minutes: 4
    - platform: numeric_state
      entity_id: sensor.energy_meter_total_watts
      above: '0'
      for:
        minutes: 6
    - platform: numeric_state
      entity_id: sensor.energy_meter_total_watts
      above: '0'
      for:
        minutes: 8
    - platform: state
      entity_id: binary_sensor.tesla_wall_connector_contactor_closed
      to: 'on'
      for:
        minutes: 2
    condition:
    - condition: state
      entity_id: binary_sensor.tesla_wall_connector_contactor_closed
      state: 'on'
    - condition: state
      entity_id: input_boolean.charging_override
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.energy_meter_total_watts
      above: '0'
    action:
    - service: number.set_value
      data_template:
        entity_id: number.lucy_charging_amps
        value: >
          {% set charging = (states('number.lucy_charging_amps')|int) %}
          {% set grid = (states('sensor.energy_meter_total_watts')|int) %}
          {% if grid > 7000 %}
            {% set result = charging - 15 | int %}
          {% elif grid > 6000 %}
            {% set result = charging - 13 | int %}
          {% elif grid > 5000 %}
            {% set result = charging - 12 | int %}
          {% elif grid > 4500 %}
            {% set result = charging - 11 | int %}
          {% elif grid > 3000 %}
            {% set result = charging - 8 | int %}
          {% elif grid > 2200 %}
            {% set result = charging - 5 | int %}
          {% elif grid > 1700 %}
            {% set result = charging - 4 | int %}
          {% elif grid > 1400 %}
            {% set result = charging - 3 | int %}
          {% elif grid > 700 %}
            {% set result = charging - 2 | int %}
          {% else %}
            {% set result = charging - 1 | int %}
          {% endif %}
          {% if result < 0 %}
            {% set result = 0 %}
          {% endif %}
          {{ result }}
    - delay:
        minutes: 1
    - service: button.press
      target:
        entity_id: button.lucy_force_data_update
    - service: notify.mobile_app_s21
      data:
        message: clear_notification
        data:
          tag: charging
    - delay:
        seconds: 10
    - service: notify.mobile_app_s21
      data:
        message: "Lucy Charging at {{ states('number.lucy_charging_amps')}} Amps"
        data:
          tag: charging