automation:
  - id: coffee_off
    alias: Coffee Off
    description: Turns off the coffee machine when on too long.
    trigger:
    - entity_id: switch.coffee_machine
      platform: state
      to: 'on'
      for:
        minutes: 30
    condition: []
    action:
      service: switch.turn_off
      data:
        entity_id:
        - switch.coffee_machine

  - id: coffee_one_off_on
    alias: Coffee One Off On
    description: Turns off the coffee machine on a date set by GUI.
    mode: single
    trigger:
    - platform: time
      at: input_datetime.coffee_time
    condition: []
    action:
    - service: switch.turn_on
      data:
        entity_id:
        - switch.coffee_machine

  - id: coffee_on_sunday
    alias: Coffee On Sunday
    description: Turns on the coffee machine on Sunday morning bike ride.
    trigger:
      platform: zone
      entity_id: person.glen
      zone: zone.daglish
      event: leave
    condition:
    - condition: time
      weekday:
      - sun
    - condition: state
      entity_id: input_boolean.holiday_mode
      state: 'off'
    - condition: time
      after: 09:30:00
      before: '12:00:00'
    - condition: zone
      entity_id: person.glen
      zone: zone.subi
    action:
      service: switch.turn_on
      data:
        entity_id:
        - switch.coffee_machine

  - id: coffee_on_weekday_morning
    alias: Coffee On Weekday Morning
    description: Turns on the coffee machine on weekdays when Glen is at yoga.
    trigger:
      platform: time
      at: 06:50:00
    condition:
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    - condition: zone
      entity_id: person.glen
      zone: zone.bby
    - condition: state
      entity_id: input_boolean.holiday_mode
      state: 'off'
    action:
      service: switch.turn_on
      data:
        entity_id:
        - switch.coffee_machine

  - id: coffee_notify
    alias: Coffee Notify
    trigger:
    - platform: numeric_state
      entity_id: sensor.coffee_power
      below: 110
    condition:
    - condition: state
      entity_id: input_boolean.coffee_notify
      state: 'off'
    - condition: time
      after: '04:30:00'
    - condition: time
      before: '17:00:00'
    - condition: state
      entity_id: switch.coffee_machine
      state: 'on'
    action:
    - delay: 00:00:16
    - condition: numeric_state
      entity_id: sensor.coffee_power
      below: 110
    - service: tts.google_translate_say
      data:
        message: 'The coffee machine is ready.'
        entity_id:
        - "media_player.bedroom_speaker"
        - "media_player.den_display"
        - "media_player.workshop_speaker"
    - service: input_boolean.turn_on
      data:
        entity_id:
        - input_boolean.coffee_notify
    - service: notify.mobile_app_s21
      data:
        message: 'The coffee machine is ready.'
        data:
          tag: coffee
          sticky: 'true'
    - service: light.turn_on
      data:
        entity_id: light.kitchen_light

  - id: coffee_notify_reset
    alias: Coffee Notify Reset on start
    trigger:
    - platform: state
      entity_id: switch.coffee_machine
      to: 'on'
    condition: []
    action:
    - service: input_boolean.turn_on
      data:
        entity_id:
        - input_boolean.coffee_notify
    - delay: 00:02:00
    - service: input_boolean.turn_off
      data:
        entity_id:
        - input_boolean.coffee_notify

  - id: coffee_phone_notify_reset
    alias: Coffee Phone Notify Reset when off
    trigger:
    - platform: state
      entity_id: switch.coffee_machine
      to: 'off'
    condition: []
    action:
      - service: notify.mobile_app_s21
        data:
          message: "clear_notification"
          data:
            tag: coffee