automation:
  - id: tesla_solar_charging_start
    alias: Tesla Solar Charging Start
    trigger:
    - platform: numeric_state
      entity_id: sensor.energy_meter_total_watts
      below: '-1000'
      for: 00:05:00
    - platform: time
      at: 09:05:00
    - platform: state
      entity_id: binary_sensor.tesla_wall_connector_vehicle_connected
      to: 'on'
    condition:
    - condition: state
      entity_id: binary_sensor.tesla_wall_connector_vehicle_connected
      state: 'on'
    - condition: state
      entity_id: input_boolean.charging_override
      state: 'off'
    - condition: template
      value_template: >-
        {{ states('sensor.lucy_battery') | int < states('number.lucy_charge_limit') | int }}
    - condition: time
      after: 09:00:00
      before: '15:00:00'
    action:
    - condition: state
      entity_id: binary_sensor.tesla_wall_connector_contactor_closed
      state: 'off'
    - service: switch.turn_on
      data:
        entity_id:
        - switch.lucy_charger
    - delay:
        minutes: 1
    - service: button.press
      target:
        entity_id: button.lucy_force_data_update
    - service: notify.mobile_app_s21
      data:
        message: clear_notification
        data:
          tag: charging
    - delay:
        seconds: 10
    - service: notify.mobile_app_s21
      data:
        message: "Lucy Started Charging at {{ states('sensor.lucy_battery')}}%"
        data:
          tag: charging

  - id: tesla_charging_stop
    alias: Tesla Charging Stop
    trigger:
    - platform: numeric_state
      entity_id: sensor.energy_meter_total_watts
      above: '1000'
      for: 00:15:00
    - platform: time
      at: '14:59'
    - platform: state
      entity_id: binary_sensor.tesla_wall_connector_contactor_closed
      to: 'on'
    condition:
      or:
        - condition: time
          before: 09:00:00
          after: '14:58:00'
        - condition: numeric_state
          entity_id: sensor.energy_meter_total_watts
          above: '500'
    action:
    - condition: state
      entity_id: binary_sensor.tesla_wall_connector_contactor_closed
      state: 'on'
    - condition: state
      entity_id: input_boolean.charging_override
      state: 'off'
    - service: switch.turn_off
      data:
        entity_id:
        - switch.lucy_charger

  - id: tesla_charging_stopped
    alias: Tesla Charging Stopped
    trigger:
    - platform: state
      entity_id: binary_sensor.tesla_wall_connector_contactor_closed
      to: 'off'
    - condition: state
      entity_id: binary_sensor.tesla_wall_connector_vehicle_connected
      state: 'on'
    action:
    - service: button.press
      target:
        entity_id: button.lucy_force_data_update
    - service: notify.mobile_app_s21
      data:
        message: clear_notification
        data:
          tag: charging
    - delay:
        seconds: 10
    - service: notify.mobile_app_s21
      data:
        message: "Lucy Stopped Charging at {{ states('sensor.lucy_battery')}}%"
        data:
          tag: charging

  - id: tesla_solar_charging_more
    alias: Tesla Solar Charging More
    mode: single
    trigger:
    - platform: numeric_state
      entity_id: sensor.energy_meter_total_watts
      below: '-900'
      for:
        minutes: 2
    - platform: state
      entity_id: binary_sensor.tesla_wall_connector_contactor_closed
      to: 'on'
      for:
        minutes: 2
    condition:
    - condition: state
      entity_id: binary_sensor.tesla_wall_connector_contactor_closed
      state: 'on'
    - condition: state
      entity_id: input_boolean.charging_override
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.energy_meter_total_watts
      below: '-900'
    action:
    - service: number.set_value
      data_template:
        entity_id: number.lucy_charging_amps
        value: >
          {% if (states('sensor.energy_meter_total_watts')|int < -3800) %}
            {% set result = (states('number.lucy_charging_amps')|float + 5 |int) %}
          {% elif (states('sensor.energy_meter_total_watts')|int < -3000) %}
            {% set result = (states('number.lucy_charging_amps')|float + 4 |int) %}
          {% elif (states('sensor.energy_meter_total_watts')|int < -2300) %}
            {% set result = (states('number.lucy_charging_amps')|float + 3 |int) %}
          {% elif (states('sensor.energy_meter_total_watts')|int < -1600) %}
            {% set result = (states('number.lucy_charging_amps')|float + 2 |int) %}
          {% else %}
            {% set result = (states('number.lucy_charging_amps')|float + 1 |int) %}
          {% endif %}
          {{ result }}
    - delay:
        minutes: 1
    - service: button.press
      target:
        entity_id: button.lucy_force_data_update
    - service: notify.mobile_app_s21
      data:
        message: clear_notification
        data:
          tag: charging
    - delay:
        seconds: 10
    - service: notify.mobile_app_s21
      data:
        message: "Lucy Charging at {{ states('number.lucy_charging_amps')}} Amps"
        data:
          tag: charging

  - id: tesla_solar_charging_less
    alias: Tesla Solar Charging less
    mode: single
    trigger:
    - platform: numeric_state
      entity_id: sensor.energy_meter_total_watts
      above: '300'
      for:
        minutes: 2
    - platform: state
      entity_id: binary_sensor.tesla_wall_connector_contactor_closed
      to: 'on'
      for:
        minutes: 2
    condition:
    - condition: state
      entity_id: binary_sensor.tesla_wall_connector_contactor_closed
      state: 'on'
    - condition: state
      entity_id: input_boolean.charging_override
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.energy_meter_total_watts
      above: '500'
    action:
    - service: number.set_value
      data_template:
        entity_id: number.lucy_charging_amps
        value: >
          {% if (states('sensor.energy_meter_total_watts')|int > 9000) %}
            {% set result = (states('number.lucy_charging_amps')|float - 13 | int) %}
          {% elif (states('sensor.energy_meter_total_watts')|int > 7500) %}
            {% set result = (states('number.lucy_charging_amps')|float - 11 | int) %}
          {% elif (states('sensor.energy_meter_total_watts')|int > 6000) %}
            {% set result = (states('number.lucy_charging_amps')|float - 9 | int) %}
          {% elif (states('sensor.energy_meter_total_watts')|int > 4000) %}
            {% set result = (states('number.lucy_charging_amps')|float - 6 | int) %}
          {% elif (states('sensor.energy_meter_total_watts')|int > 3100) %}
            {% set result = (states('number.lucy_charging_amps')|float - 5 | int) %}
          {% elif (states('sensor.energy_meter_total_watts')|int > 2400) %}
            {% set result = (states('number.lucy_charging_amps')|float - 4 | int) %}
          {% elif (states('sensor.energy_meter_total_watts')|int > 1700) %}
            {% set result = (states('number.lucy_charging_amps')|float - 3 | int) %}
          {% elif (states('sensor.energy_meter_total_watts')|int > 1400) %}
            {% set result = (states('number.lucy_charging_amps')|float - 2 | int) %}
          {% else %}
            {% set result = (states('number.lucy_charging_amps')|float - 1 | int) %}
          {% endif %}
          {% if result < 0 %}
            {% set result = 0 %}
          {% endif %}
          {{ result }}
    - delay:
        minutes: 1
    - service: button.press
      target:
        entity_id: button.lucy_force_data_update
    - service: notify.mobile_app_s21
      data:
        message: clear_notification
        data:
          tag: charging
    - delay:
        seconds: 10
    - service: notify.mobile_app_s21
      data:
        message: "Lucy Charging at {{ states('number.lucy_charging_amps')}} Amps"
        data:
          tag: charging