automation:
  - id: tesla_solar_charging_start
    alias: Tesla Solar Charging Start
    trigger:
    - platform: numeric_state
      entity_id: sensor.energy_meter_total_watts
      below: '-1500'
      for: 00:05:00
    - platform: time
      at: 09:05:00
    condition:
    - condition: state
      entity_id: binary_sensor.tesla_wall_connector_vehicle_connected
      state: 'on'
    - condition: state
      entity_id: input_boolean.charging_override
      state: 'off'
    - condition: template
      value_template: >-
        {{ states('sensor.lucy_battery') | int < states('number.lucy_charge_limit') | int }}
    - condition: time
      after: 09:00:00
      before: '15:00:00'
    action:
    - condition: state
      entity_id: binary_sensor.tesla_wall_connector_contactor_closed
      state: 'off'
    - service: switch.turn_on
      data:
        entity_id:
        - switch.lucy_charger
    - delay:
        minutes: 1
    - service: button.press
      target:
        entity_id: button.lucy_force_data_update
    - service: notify.mobile_app_s21
      data:
        message: clear_notification
        data:
          tag: charging
    - delay:
        seconds: 10
    - service: notify.mobile_app_s21
      data:
        message: "Lucy Started Charging at {{ states('sensor.lucy_battery')}}%"
        data:
          tag: charging

  - id: tesla_charging_stop
    alias: Tesla Charging Stop
    trigger:
    - platform: numeric_state
      entity_id: sensor.energy_meter_total_watts
      above: '500'
      for: 00:05:00
    - platform: time
      at: '14:59'
    - platform: state
      entity_id: binary_sensor.tesla_wall_connector_contactor_closed
      to: 'on'
    condition:
      or:
        - condition: time
          before: 09:00:00
          after: '14:58:00'
        - condition: numeric_state
          entity_id: sensor.energy_meter_total_watts
          above: '500'
    action:
    - condition: state
      entity_id: binary_sensor.tesla_wall_connector_contactor_closed
      state: 'on'
    - condition: state
      entity_id: input_boolean.charging_override
      state: 'off'
    - service: switch.turn_off
      data:
        entity_id:
        - switch.lucy_charger

  - id: tesla_solar_charging_set
    alias: Tesla Solar Charging Set
    trigger:
    - platform: state
      entity_id: input_number.tesla_charging_amps
    - platform: state
      entity_id: binary_sensor.tesla_wall_connector_contactor_closed
      to: 'on'
      for: 00:01:00
    condition: []
    action:
    - service: button.press
      target:
        entity_id: button.lucy_force_data_update
    - condition: state
      entity_id: input_boolean.charging_override
      state: 'off'
    - condition: state
      entity_id: binary_sensor.tesla_wall_connector_contactor_closed
      state: 'on'
    - service: number.set_value
      data_template:
        entity_id: number.lucy_charging_amps
        value: "{{ states('input_number.tesla_charging_amps') }}"
    - delay:
        minutes: 1
    - service: button.press
      target:
        entity_id: button.lucy_force_data_update

  - id: tesla_charging_stopped
    alias: Tesla Charging Stopped
    trigger:
    - platform: state
      entity_id: binary_sensor.tesla_wall_connector_contactor_closed
      to: 'off'
    condition: []
    action:
    - service: button.press
      target:
        entity_id: button.lucy_force_data_update
    - service: notify.mobile_app_s21
      data:
        message: clear_notification
        data:
          tag: charging
    - delay:
        seconds: 10
    - service: notify.mobile_app_s21
      data:
        message: "Lucy Stopped Charging at {{ states('sensor.lucy_battery')}}%"
        data:
          tag: charging