binary_sensor:
  - platform: bayesian
    name: 'Nat Presence'
    device_class: presence
    prior: 0.7
    probability_threshold: 0.8
    observations:
      - entity_id: 'device_tracker.nat_iphonedetect'
        prob_given_true: 0.8
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.nat_unifi'
        prob_given_true: 0.9
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'home'