light:
  - platform: switch
    name: FL Light
    entity_id: switch.lounge_frontleft
  - platform: switch
    name: FR Light
    entity_id: switch.lounge_frontright
  - platform: switch
    name: RL Light
    entity_id: switch.lounge_rearleft
  - platform: switch
    name: RR Light
    entity_id: switch.lounge_rearlright

homeassistant:
  customize:
    light.lounge_frontleft:
      icon: mdi:lightbulb
    light.lounge_frontright:
      icon: mdi:lightbulb
    light.lounge_rearleft:
      icon: mdi:lightbulb
    light.lounge_rearright:
      icon: mdi:lightbulb