sensor:
  - platform: time_date
    display_options:
      - 'date_time'
      - 'time'
  - platform: template
    sensors:
      lounge_hub_activity:
        value_template: '{{ state_attr("remote.lounge_hub", "current_activity") }}'
        friendly_name: 'Harmony Activity'

  - platform: template
    sensors:
      energy_import:
        friendly_name: Synergy Import Tariff
        unit_of_measurement: AUD/kWh
        value_template: >
          {% set tariff = { "PE": 0.5, "OP": 0.22, "SOP": 0.08 } %}
          {% if ((9 < (now().hour)) %}
            {{ tariff.OP }}
          {% elif ((15 < (now().hour)) %}
            {{ tariff.SOP }}
          {% elif ((21 < (now().hour)) %}
            {{ tariff.PE }}
          {% else %}
            {{ tariff.OP }}
          {% endif %}

  - platform: template
    sensors:
      energy_export:
        friendly_name: Synergy Export Tariff
        unit_of_measurement: AUD/kWh
        value_template: >
          {% set tariff = { "PE": 0.25, "OP": 0.1} %}
           {% if ((15 < (now().hour)) %}
            {{ tariff.PE }}
          {% else %}
            {{ tariff.OP }}
          {% endif %}